import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth,onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { collection,deleteDoc,doc,getDoc,getDocs,getFirestore,updateDoc } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),labels={member:'Member',pro:'Pro TEACHR',admin:'Admin',superadmin:'Superadmin'};
let currentRole='member',currentUid='',usersByUid=new Map(),activeUsageUid='';
const table=document.getElementById('userTable'),status=document.getElementById('adminStatus'),usagePanel=document.getElementById('usagePanel'),usageTable=document.getElementById('usageTable');
const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char])),date=value=>value?.toDate?value.toDate().toLocaleDateString('en-GB'):value?new Date(value).toLocaleString('en-GB'):'—';
function setStatus(message,type=''){status.textContent=message;status.dataset.type=type}
function normalise(item){const data=item.data();return{uid:item.id,...data,role:labels[data.role]?data.role:'member',plan:data.plan==='pro'?'pro':'free',suspended:data.suspended===true}}
function unlimited(user){return ['pro','admin','superadmin'].includes(user.role)||user.plan==='pro'}
function actions(user){const protectedUser=user.email?.toLowerCase()==='admin@lawal.org'||user.uid===currentUid;if(protectedUser)return'<span class="user-email">Protected</span>';const roles=currentRole==='superadmin'?['member','pro','admin']:['member','pro'],options=roles.map(role=>`<option value="${role}" ${user.role===role?'selected':''}>${labels[role]}</option>`).join('');return`<div class="actions"><select data-role="${esc(user.uid)}">${options}</select><button data-toggle="${esc(user.uid)}" data-suspended="${user.suspended}">${user.suspended?'Restore':'Suspend'}</button><button class="danger" data-delete="${esc(user.uid)}">Remove</button></div>`}
function render(users){usersByUid=new Map(users.map(user=>[user.uid,user]));document.getElementById('statTotal').textContent=users.length;document.getElementById('statMembers').textContent=users.filter(u=>u.role==='member').length;document.getElementById('statPros').textContent=users.filter(u=>u.role==='pro'||u.plan==='pro').length;document.getElementById('statAdmins').textContent=users.filter(u=>['admin','superadmin'].includes(u.role)).length;document.getElementById('statSuspended').textContent=users.filter(u=>u.suspended).length;table.innerHTML=users.length?users.map(user=>`<tr><td><span class="user-name">${esc(user.displayName||'TEACHR Member')}</span><span class="user-email">${esc(user.email||'No email')}</span></td><td><span class="pill ${user.role}">${labels[user.role]}</span></td><td><span class="pill ${user.plan}">${user.plan==='pro'?'Pro':'Free'}</span></td><td><span class="pill ${user.suspended?'suspended':'active'}">${user.suspended?'Suspended':'Active'}</span></td><td>${date(user.createdAt)}</td><td><button class="usage-button" data-usage="${esc(user.uid)}" type="button">${unlimited(user)?'Unlimited · View':'View Credits'}</button></td><td>${actions(user)}</td></tr>`).join(''):'<tr><td colspan="7">No user profiles found.</td></tr>'}
async function loadUsers(){setStatus('Loading users…');try{const snap=await getDocs(collection(db,'users')),users=snap.docs.map(normalise).sort((a,b)=>(a.email||'').localeCompare(b.email||''));render(users);setStatus(`${users.length} account${users.length===1?'':'s'} loaded.`)}catch(error){console.error(error);setStatus('Unable to load user profiles. Check the deployed Firestore rules.','error')}}
async function adminRequest(path,options={}){const user=auth.currentUser;if(!user)throw new Error('Administrator sign-in is required');const token=await user.getIdToken();const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Admin request failed');return payload}
function renderUsage(data){const user=usersByUid.get(data.uid)||data,isUnlimited=unlimited(data),balance=Number(data.credits?.balance)||0;document.getElementById('usageMemberName').textContent=data.displayName||user.displayName||'TEACHR Member';document.getElementById('usageMemberEmail').textContent=data.email||user.email||'No email';document.getElementById('usageSummary').innerHTML=`<article><span>Credit balance</span><strong>${balance}</strong></article><article><span>Access</span><strong>${isUnlimited?'Unlimited':'Credit based'}</strong></article><article><span>Total admin grants</span><strong>${Number(data.credits?.totalGranted)||0}</strong></article>`;usageTable.innerHTML=(data.ledger||[]).length?(data.ledger||[]).map(entry=>`<tr><td>${date(entry.createdAt)}</td><td><strong>+${Number(entry.amount)||0}</strong></td><td>${esc(entry.reason||'—')}</td><td>${esc(entry.adminEmail||entry.adminUid||'Admin')}</td><td>${Number(entry.balanceAfter)||0}</td></tr>`).join(''):'<tr><td colspan="5">No admin Credit grants recorded.</td></tr>';usagePanel.hidden=false}
async function showUsage(uid,{scroll=true}={}){activeUsageUid=uid;setStatus('Loading Credits…');try{const data=await adminRequest(`/api/admin/credits?uid=${encodeURIComponent(uid)}`);renderUsage(data);if(scroll)usagePanel.scrollIntoView({behavior:'smooth',block:'start'});setStatus('Credits loaded.')}catch(error){console.error(error);setStatus(error.message||'Unable to load Credits.','error')}}
async function addCredits(){if(!activeUsageUid)return;const amount=Number(document.getElementById('creditAmount').value),reason=document.getElementById('creditReason').value.trim();if(!Number.isInteger(amount)||amount<1||amount>1000)return setStatus('Enter a Credit amount from 1 to 1000.','error');if(!reason)return setStatus('Enter a reason for this Credit grant.','error');if(!confirm(`Add ${amount} Credit${amount===1?'':'s'} to this account?`))return;const button=document.getElementById('addCredits');button.disabled=true;setStatus('Adding Credits…');try{await adminRequest('/api/admin/credits/add',{method:'POST',body:JSON.stringify({uid:activeUsageUid,amount,reason})});document.getElementById('creditReason').value='';await showUsage(activeUsageUid,{scroll:false});setStatus(`${amount} Credit${amount===1?'':'s'} added.`)}catch(error){console.error(error);setStatus(error.message||'Unable to add Credits.','error')}finally{button.disabled=false}}
document.getElementById('refreshUsers').addEventListener('click',loadUsers);document.getElementById('closeUsage').addEventListener('click',()=>{usagePanel.hidden=true;activeUsageUid=''});document.getElementById('addCredits').addEventListener('click',addCredits);
table.addEventListener('change',async event=>{const select=event.target.closest('[data-role]');if(!select)return;select.disabled=true;const role=select.value;try{await updateDoc(doc(db,'users',select.dataset.role),{role,plan:role==='pro'?'pro':'free',updatedAt:new Date()});await loadUsers()}catch(error){console.error(error);setStatus('Unable to change this role.','error');select.disabled=false}});
table.addEventListener('click',async event=>{const usage=event.target.closest('[data-usage]'),toggle=event.target.closest('[data-toggle]'),remove=event.target.closest('[data-delete]');if(usage)return showUsage(usage.dataset.usage);if(toggle){toggle.disabled=true;const suspended=toggle.dataset.suspended==='true';try{await updateDoc(doc(db,'users',toggle.dataset.toggle),{suspended:!suspended,accountStatus:suspended?'active':'suspended',updatedAt:new Date()});await loadUsers()}catch(error){console.error(error);setStatus('Unable to change account status.','error');toggle.disabled=false}}if(remove){if(!confirm('Remove this TEACHR profile? The Firebase sign-in account will remain.'))return;remove.disabled=true;try{await deleteDoc(doc(db,'users',remove.dataset.delete));await loadUsers()}catch(error){console.error(error);setStatus('Unable to remove this profile.','error');remove.disabled=false}}});
onAuthStateChanged(auth,async user=>{if(!user){location.replace('index.html');return}currentUid=user.uid;try{const own=(await getDoc(doc(db,'users',user.uid))).data()||{};currentRole=user.email?.toLowerCase()==='admin@lawal.org'?'superadmin':own.role;if(!['admin','superadmin'].includes(currentRole)){location.replace('index.html');return}document.getElementById('adminRole').textContent=labels[currentRole];await loadUsers()}catch(error){console.error(error);setStatus('Administrator access could not be verified.','error')}});
