import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {getFirestore,doc,getDoc} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),buttons=[...document.querySelectorAll('.billing-plan')],status=document.getElementById('upgrade-status'),api=window.TEACHR_PAYMENT?.appsScriptUrl||'';
const params=new URLSearchParams(location.search),requestedReturn=params.get('return')||'',returnTo=/^index\.html(?:\?|#|$)/.test(requestedReturn)?requestedReturn:'index.html#workspace';
let activationTimer=null;

function setStatus(message,type=''){status.textContent=message;status.dataset.type=type;}
function setButtons(enabled){buttons.forEach(button=>button.disabled=!enabled);}
function planActivated(profile,plan,before){const activePlan=String(profile?.plan||'free').toLowerCase();if(plan==='payg'){const balance=Number(profile?.credits?.balance??profile?.creditBalance??NaN);return Number.isFinite(balance)&&(!Number.isFinite(before.creditBalance)||balance>before.creditBalance);}return activePlan===plan&&activePlan!==before.plan;}
async function watchForActivation(user,plan,before){if(activationTimer)clearInterval(activationTimer);let attempts=0;const check=async()=>{attempts+=1;try{const snapshot=await getDoc(doc(db, 'users', user.uid));if(snapshot.exists()&&planActivated(snapshot.data(),plan,before)){if(activationTimer)clearInterval(activationTimer);activationTimer=null;setStatus('Payment confirmed. Restoring your TEACHR workspace.','success');setTimeout(()=>location.replace(returnTo),500);return;}}catch(error){console.warn('TEACHR activation check failed',error);}if(attempts>=60){if(activationTimer)clearInterval(activationTimer);activationTimer=null;setStatus('Payment may still be processing. Refresh this page shortly to check your updated access.');}};await check();if(!activationTimer&&attempts<60)activationTimer=setInterval(check,2000);}

onAuthStateChanged(auth,async user=>{if(!user){setStatus('Please sign in before purchasing Credits or a plan.','error');setTimeout(()=>location.replace('index.html'),1000);return;}if(!api){setStatus('Payment setup is awaiting the TEACHR checkout web-app URL.','error');return;}let before={plan:'free',creditBalance:NaN};try{const snapshot=await getDoc(doc(db, 'users', user.uid));if(snapshot.exists()){const profile=snapshot.data();before={plan:String(profile?.plan||'free').toLowerCase(),creditBalance:Number(profile?.credits?.balance??profile?.creditBalance??NaN)};}}catch(error){console.warn('TEACHR pre-checkout profile read failed',error);}setStatus(`Signed in as ${user.email}`);setButtons(true);buttons.forEach(button=>{button.onclick=()=>{const plan=button.dataset.plan;if(!['payg','standard','pro','premium'].includes(plan))return;const checkoutUrl=`${api}?action=tier-pay&plan=${encodeURIComponent(plan)}&uid=${encodeURIComponent(user.uid)}&email=${encodeURIComponent(user.email||'')}`,checkoutWindow=window.open(checkoutUrl,'_blank','noopener,noreferrer');if(!checkoutWindow){setStatus('Your browser blocked the checkout window. Allow pop-ups for TEACHR and try again.','error');return;}setStatus('Stripe checkout opened in a new secure tab. Complete payment there, then return to TEACHR.');watchForActivation(user,plan,before);};});});
