/* TEACHR universal Credit presentation and upgrade guidance. */
(function initialiseUsageUi(){
  const generatingTools=new Set(window.TEACHR_CREDIT_USAGE?.GENERATING_TOOL_IDS||[]);const DRAFT_KEY='teachr-upgrade-draft-v1';
  function activeToolId(){return document.querySelector('.tool-card.active')?.dataset.tool||'lesson';}
  function formValues(){const form=document.getElementById('builderForm');return form?Object.fromEntries(new FormData(form).entries()):{};}
  function saveDraft(){const toolId=activeToolId();if(!generatingTools.has(toolId))return;try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify({toolId,values:formValues(),savedAt:Date.now()}));}catch{}}
  function restoreDraft(){let draft;try{draft=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');}catch{return;}if(!draft?.toolId||!draft?.values||!generatingTools.has(draft.toolId))return;document.querySelector(`.tool-card[data-tool="${draft.toolId}"]`)?.click();const form=document.getElementById('builderForm');if(!form)return;Object.entries(draft.values).forEach(([name,value])=>{const field=form.elements.namedItem(name);if(field&&'value'in field)field.value=value;});try{sessionStorage.removeItem(DRAFT_KEY);}catch{}}
  function ensureSummary(){const intro=document.querySelector('#appDashboard .app-intro');if(!intro)return null;let summary=document.getElementById('appUsageSummary');if(!summary){summary=document.createElement('p');summary.id='appUsageSummary';summary.className='app-usage-summary';summary.setAttribute('role','status');summary.setAttribute('aria-live','polite');intro.appendChild(summary);}return summary;}
  function ensureDashboardBalance(){const dashboard=document.getElementById('appDashboard'),intro=dashboard?.querySelector('.app-intro');if(!dashboard||!intro)return null;let card=document.getElementById('appCreditBalance');if(!card){card=document.createElement('section');card.id='appCreditBalance';card.className='app-credit-balance';card.setAttribute('role','status');card.setAttribute('aria-live','polite');intro.insertAdjacentElement('afterend',card);}return card;}
  function ensureToolBadge(card){let badge=card.querySelector('.app-tool-usage');if(!badge){badge=document.createElement('span');badge.className='app-tool-usage';card.appendChild(badge);}return badge;}
  function ensureBuilderStatus(){const header=document.querySelector('#builderPanel .builder-header > div');if(!header)return null;let status=document.getElementById('builderUsageStatus');if(!status){status=document.createElement('p');status.id='builderUsageStatus';status.className='builder-usage-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');header.appendChild(status);}return status;}
  function updateGenerateAction(snapshot){const toolId=activeToolId(),label=document.getElementById('generateLabel');if(!label||!generatingTools.has(toolId))return;const exhausted=snapshot.status==='ready'&&!snapshot.unlimited&&snapshot.creditsRemaining===0;if(exhausted){label.textContent='Upgrade to continue';saveDraft();return;}const config={lesson:'Generate lesson',worksheet:'Generate worksheet',quiz:'Generate assessment',differentiate:'Differentiate activity',curriculum:'Build curriculum map',revision:'Build revision pack',presentation:'Create Google Slides'};label.textContent=config[toolId]||'Generate';}
  function renderDashboardBalance(snapshot){const card=ensureDashboardBalance();if(!card)return;card.classList.remove('is-unlimited','is-exhausted','is-error');if(snapshot.status==='loading'){card.innerHTML='<div><span>TEACHR CREDITS</span><strong>Checking…</strong></div><p>Your Credits are shared across all seven generation tools.</p>';return;}if(snapshot.status==='error'){card.classList.add('is-error');card.innerHTML='<div><span>TEACHR CREDITS</span><strong>Unavailable</strong></div><p>Your Credit balance could not be loaded. Try again shortly.</p>';return;}if(snapshot.status==='ready'&&snapshot.unlimited){card.classList.add('is-unlimited');card.innerHTML='<div><span>TEACHR CREDITS</span><strong>Unlimited</strong></div><p>Your account includes unlimited generations across all seven TEACHR tools.</p>';return;}if(snapshot.status==='ready'){const remaining=Number(snapshot.creditsRemaining)||0;card.classList.toggle('is-exhausted',remaining===0);card.innerHTML=`<div><span>TEACHR CREDITS</span><strong>${remaining}</strong><small>Credits remaining</small></div><p>1 successful generation = 1 Credit. Your Credits work across all seven TEACHR tools.</p>`;return;}card.innerHTML='';}
  function renderToolCards(snapshot){document.querySelectorAll('.app-tool-card[data-tool]').forEach(card=>{if(!generatingTools.has(card.dataset.tool))return;const badge=ensureToolBadge(card);card.classList.remove('usage-exhausted','usage-unavailable');if(snapshot.status==='loading')badge.textContent='Checking Credits…';else if(snapshot.status==='error'){badge.textContent='Credits unavailable';card.classList.add('usage-unavailable');}else if(snapshot.status==='ready'&&snapshot.unlimited)badge.textContent='Unlimited';else if(snapshot.status==='ready'){badge.textContent=`${snapshot.creditsRemaining} Credits`;card.classList.toggle('usage-exhausted',snapshot.creditsRemaining===0);}else badge.textContent='';});}
  function renderActiveTool(snapshot){const status=ensureBuilderStatus();if(!status)return;status.className='builder-usage-status';if(snapshot.status==='loading')status.textContent='Checking your TEACHR Credits…';else if(snapshot.status==='error'){status.textContent='TEACHR Credits are temporarily unavailable.';status.classList.add('usage-error');}else if(snapshot.status==='ready'&&snapshot.unlimited)status.textContent='Unlimited generations with Pro TEACHR.';else if(snapshot.status==='ready'){status.textContent=snapshot.creditsRemaining===0?'No Credits remaining. Pro unlocks unlimited generations across every TEACHR tool.':`${snapshot.creditsRemaining} TEACHR Credits remaining. Each successful generation uses 1 Credit.`;status.classList.toggle('usage-exhausted',snapshot.creditsRemaining===0);}else status.textContent='';updateGenerateAction(snapshot);}
  function render(snapshot){const summary=ensureSummary();if(summary)summary.textContent=snapshot.status==='ready'?(snapshot.unlimited?'Your Pro account includes unlimited generations.':`${snapshot.creditsRemaining} TEACHR Credits available across all seven generation tools.`):snapshot.status==='error'?'TEACHR Credits are temporarily unavailable.':'Loading your TEACHR Credits…';renderDashboardBalance(snapshot);renderToolCards(snapshot);renderActiveTool(snapshot);}
  window.addEventListener('teachr:usagechange',event=>render(event.detail||{}));document.addEventListener('input',event=>{if(event.target.closest('#builderForm'))saveDraft();});document.addEventListener('change',event=>{if(event.target.closest('#builderForm'))saveDraft();});document.addEventListener('click',event=>{if(!event.target.closest('.app-tool-card[data-tool]'))return;queueMicrotask(()=>renderActiveTool(window.TEACHR_USAGE?.getSnapshot?.()||{}));});window.addEventListener('teachr:authchange',event=>{if(event.detail?.status==='signed-in'){queueMicrotask(()=>{restoreDraft();render(window.TEACHR_USAGE?.getSnapshot?.()||{status:'loading'});});}});
  const style=document.createElement('style');style.textContent=`.app-usage-summary{margin-top:8px!important;color:#9eb2cc!important}.app-credit-balance{display:flex;align-items:center;justify-content:space-between;gap:24px;margin:0 0 24px;padding:20px 24px;border:1px solid rgba(92,225,161,.25);border-radius:18px;background:linear-gradient(135deg,rgba(92,225,161,.09),rgba(83,170,255,.06));box-shadow:0 14px 36px rgba(0,0,0,.12)}.app-credit-balance>div{display:grid;grid-template-columns:auto auto;align-items:baseline;column-gap:10px;min-width:210px}.app-credit-balance span{grid-column:1/-1;color:#75e4ae;font-size:10px;font-weight:800;letter-spacing:.12em}.app-credit-balance strong{font-size:34px;line-height:1;color:#fff}.app-credit-balance small{color:#9eb2cc;font-size:11px;font-weight:700}.app-credit-balance p{margin:0;max-width:520px;color:#9eb2cc;font-size:12px;line-height:1.55}.app-credit-balance.is-unlimited strong{font-size:25px;color:#75e4ae}.app-credit-balance.is-exhausted{border-color:rgba(255,180,93,.38);background:rgba(255,180,93,.08)}.app-credit-balance.is-exhausted span,.app-credit-balance.is-exhausted strong{color:#ffc779}.app-credit-balance.is-error{border-color:var(--line);background:rgba(255,255,255,.035)}.app-tool-card{position:relative}.app-tool-usage{position:absolute;top:18px;right:18px;left:auto;bottom:auto;max-width:calc(100% - 92px);padding:5px 8px;border:1px solid rgba(92,225,161,.24);border-radius:999px;background:rgba(92,225,161,.08);color:#75e4ae;font-size:9px;font-weight:800;line-height:1.2;letter-spacing:.03em;white-space:nowrap;z-index:2}.app-tool-card.usage-exhausted{border-color:rgba(255,180,93,.35)}.app-tool-card.usage-exhausted .app-tool-usage{border-color:rgba(255,180,93,.35);background:rgba(255,180,93,.1);color:#ffc779}.app-tool-card.usage-unavailable .app-tool-usage{border-color:var(--line);background:rgba(255,255,255,.035);color:#8195b1}.builder-usage-status{margin:10px 0 0;color:#75e4ae;font-size:11px;font-weight:700}.builder-usage-status.usage-exhausted,.builder-usage-status.usage-error{color:#ffc779}@media(max-width:640px){.app-credit-balance{align-items:flex-start;flex-direction:column;gap:10px;padding:18px}.app-credit-balance>div{min-width:0}.app-tool-usage{top:14px;right:14px;max-width:calc(100% - 78px);font-size:8px}}`;document.head.appendChild(style);
})();
