const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const usage = require('../generation-usage.js');
const adjusted = usage.normaliseUsageRecord('lesson', { successfulGenerations: 3, allowance: 8 });
assert.equal(adjusted.successfulGenerations, 3);
assert.equal(adjusted.allowance, 8);
assert.equal(usage.remainingGenerations('lesson', adjusted), 5);
const resetAllowance = adjusted.successfulGenerations + usage.FREE_GENERATIONS_PER_TOOL;
assert.equal(resetAllowance - adjusted.successfulGenerations, 3);
assert.deepEqual(usage.GENERATING_TOOL_IDS, ['lesson','worksheet','quiz','differentiate','curriculum','revision','parent']);
const service = fs.readFileSync(path.join(__dirname, '../server/admin-usage.js'), 'utf8');
assert.match(service, /\['admin', 'superadmin'\]\.includes\(role\)/);
assert.match(service, /tool === 'all'/);
assert.match(service, /record\.allowance \+ amount/);
assert.match(service, /record\.successfulGenerations \+ FREE_GENERATIONS_PER_TOOL/);
assert.match(service, /lastAdminAdjustment/);
assert.match(service, /amount < 1 \|\| amount > 1000/);
assert.doesNotMatch(service, /successfulGenerations:\s*0/);
const server = fs.readFileSync(path.join(__dirname, '../server/index.js'), 'utf8');
assert.match(server, /\/api\/admin\/usage-adjustment/, 'server must expose protected quota mutation endpoint');
assert.match(server, /service\.adjust\(req/, 'mutation endpoint must use admin usage service');
assert.match(server, /service\.readUsage\(req/, 'usage read endpoint must use admin usage service');
const admin = fs.readFileSync(path.join(__dirname, '../admin.js'), 'utf8');
assert.match(admin, /tool,'add'/, 'per-tool grant control must be wired');
assert.match(admin, /adjustUsage\(reset\.dataset\.reset,'reset'\)/, 'per-tool reset control must pass the selected tool to reset');
assert.match(admin, /getIdToken\(\)/, 'admin mutations must authenticate to backend');
assert.match(admin, /'all','add'/, 'shared all-tools grant must be wired');
assert.match(admin, /'all','reset'/, 'all-tools reset must be wired');
assert.match(admin, /confirm\(/, 'quota changes must require confirmation');
const production = fs.readFileSync(path.join(__dirname, '../admin-production-api.js'), 'utf8');
assert.match(production, /documents:commit/, 'production adapter must use an atomic Firestore commit');
assert.match(production, /\/api\/admin\/usage-adjustment/, 'production adapter must intercept quota mutations');
assert.match(production, /Math\.max\(currentAllowance,used\)\+amount/, 'production grants must preserve history and extend the current entitlement');
assert.match(production, /action==='reset'\?used\+3/, 'production reset must preserve history and grant three fresh uses');
assert.match(production, /adminUid/, 'production writes must carry administrator audit identity');
assert.match(production, /Authorization:token/, 'production writes must use the Firebase ID token so Firestore rules remain authoritative');
const html = fs.readFileSync(path.join(__dirname, '../admin.html'), 'utf8');
assert.match(html, /id="bulkAmount"/);
assert.match(html, /id="grantAll"/);
assert.match(html, /id="resetAll"/);
const enforcement = fs.readFileSync(path.join(__dirname, '../server/usage-enforcement.js'), 'utf8');
assert.match(enforcement, /record\.successfulGenerations\+1/);
assert.match(enforcement, /record\.allowance-successfulGenerations/);
console.log('Admin usage controls Stage 3 tests passed.');
