const fs=require('fs');const assert=require('assert');
const chat=fs.readFileSync('ai-chat-panel.js','utf8');
const auth=fs.readFileSync('teachr-auth.js','utf8');
const rules=fs.readFileSync('firestore.rules','utf8');
const css=fs.readFileSync('ai-chat-panel.css','utf8');
assert(chat.includes("stage:5"),'chat panel must identify Stage 5');
assert(chat.includes('Recent Chats'),'Stage 5 must expose Recent Chats');
assert(chat.includes('persistConversation'),'successful chat must be persisted');
assert(chat.includes('saveChatConversation'),'chat panel must save conversations through auth service');
assert(chat.includes('listChatConversations'),'chat panel must load signed-in user history');
assert(chat.includes('deleteChatConversation'),'chat panel must support deleting a conversation');
assert(chat.includes("prompt('Rename chat'"),'chat panel must support renaming a conversation');
assert(chat.includes('currentConversation=null'),'New Chat must detach from the prior saved conversation');
assert(auth.includes("'chatConversations'"),'Firestore client must use the private chatConversations collection');
assert(auth.includes('orderBy(\'updatedAt\',\'desc\')'),'recent chats must be newest first');
assert(auth.includes('limit(20)'),'recent chat retrieval must be bounded');
assert(auth.includes('messages.slice(-40)'),'persisted message history must be bounded');
assert(rules.includes('match /chatConversations/{conversationId}'),'Firestore rules must cover chat conversations');
assert(rules.includes('request.auth.uid == uid'),'chat history must be restricted to its signed-in owner');
assert(css.includes('.teachr-chat-history'),'recent chat UI must be styled');
console.log('AI chat Stage 5 conversation history tests passed');