const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('ai-chat-panel.js','utf8');
const css=fs.readFileSync('ai-chat-panel.css','utf8');
assert(js.includes("link.href='upgrade.html'"));
assert(js.includes("error?.code==='CHAT_LIMIT_REACHED'"));
assert(js.includes('navigator.clipboard.writeText(text)'));
assert(js.includes("role==='assistant'&&extraClass!=='pending'&&extraClass!=='error'"));
assert(css.includes('.teachr-chat-copy'));
assert(css.includes('.teachr-chat-upgrade'));
console.log('chat UX static checks passed');
