const CONFIG={SITE_URL:'https://teachr.uk/',FIREBASE_PROJECT_ID:'teachr-bf740',CURRENCY:'GBP'};
function doGet(e){try{const action=(e&&e.parameter&&e.parameter.action)||'';if(action==='tier-pay')return startTierCheckout_(e.parameter||{});if(action==='tier-return')return finishTierCheckout_(e.parameter||{});if(action==='tier-cancel')return redirectPage_(CONFIG.SITE_URL+'upgrade.html?upgrade=cancelled','Payment cancelled');throw new Error('Unsupported action.');}catch(error){return messagePage_('TEACHR checkout error',error.message);}}
function firestoreUser_(uid){const url='https://firestore.googleapis.com/v1/projects/'+CONFIG.FIREBASE_PROJECT_ID+'/databases/(default)/documents/users/'+encodeURIComponent(uid),response=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(response.getResponseCode()!==200)throw new Error('TEACHR user profile was not found.');return JSON.parse(response.getContentText());}
function firestoreString_(document,field){return document&&document.fields&&document.fields[field]?String(document.fields[field].stringValue||''):'';}
function stripeRequest_(path,method,payload){const secret=PropertiesService.getScriptProperties().getProperty('STRIPE_SECRET_KEY');if(!secret)throw new Error('Stripe credentials are not configured.');const options={method,headers:{Authorization:'Bearer '+secret,Accept:'application/json'},muteHttpExceptions:true};if(payload!==undefined){options.payload=payload;options.contentType='application/x-www-form-urlencoded';}const response=UrlFetchApp.fetch('https://api.stripe.com'+path,options),body=JSON.parse(response.getContentText()||'{}');if(response.getResponseCode()>=300)throw new Error('Stripe request failed: '+clean_(body.error&&body.error.message));return body;}
function redirectPage_(url,title){const safeUrl=escapeHtml_(url),safeTitle=escapeHtml_(title),html='<!doctype html><html><head><base target="_top"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+safeTitle+'</title><style>body{margin:0;background:#f5f7fb;color:#172033;font:16px/1.5 Arial,sans-serif}.card{box-sizing:border-box;max-width:520px;margin:12vh auto;padding:32px;border:1px solid #dfe5ef;border-radius:18px;background:#fff;box-shadow:0 18px 50px rgba(30,42,70,.12)}.eyebrow{margin:0 0 8px;color:#6558d3;font-size:12px;font-weight:800;letter-spacing:.12em}.card h1{margin:0 0 12px;font-size:28px}.card p{margin:0 0 24px}.button{display:block;padding:15px 20px;border-radius:10px;background:#2f276f;color:#fff!important;font-weight:800;text-align:center;text-decoration:none}.note{margin:16px 0 0!important;color:#5e687b;font-size:13px}</style></head><body><main class="card"><p class="eyebrow">TEACHR SECURE CHECKOUT</p><h1>'+safeTitle+'</h1><p>Stripe checkout must open in the main browser window.</p><a class="button" href="'+safeUrl+'" target="_top" rel="noopener">Continue securely to Stripe</a><p class="note">You will return to TEACHR after checkout.</p></main></body></html>';return HtmlService.createHtmlOutput(html).setTitle(title);}
function messagePage_(title,message){return HtmlService.createHtmlOutput('<!doctype html><html><head><meta charset="utf-8"><title>'+escapeHtml_(title)+'</title></head><body><h1>'+escapeHtml_(title)+'</h1><p>'+escapeHtml_(message)+'</p></body></html>').setTitle(title);}
function escapeHtml_(value){return String(value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function clean_(value){return String(value||'').replace(/[<>]/g,'').trim().slice(0,500);}
